name: 'ItsMyBot-Plugin'
main: studio.itsmy.itsmybot.ItsMyBotPlugin
version: '1.0.0'
api-version: 1.8

softdepend:
  - Vault
  - LuckPerms
  - PlaceholderAPI

commands:
  discord:
    description: Manage your Discord account
  link:
    description: Link your Discord account
  unlink:
    description: Unlink your Discord account

permissions:
  itsmybot.link:
    description: 'Allows the player to link their Discord account'
    default: true
  itsmybot.unlink:
    description: 'Allows the player to unlink their Discord account'
    default: true
  itsmybot.claim:
    description: 'Allows the player to claim their Discord rewards'
    default: true
  itsmybot.reload:
    description: 'Allows the player to reload the plugin configuration'
    default: op